import 'package:hugeicons/hugeicons.dart';

class GIcons {
  static const searchIcon = HugeIcons.strokeRoundedSearch01;
  static const homeIcon = HugeIcons.strokeRoundedHome04;
  static const myOrderIcon = HugeIcons.strokeRoundedShoppingBag01;
  static const settingsIcon = HugeIcons.strokeRoundedSettings02;
  static const filterIcon = HugeIcons.strokeRoundedFilterHorizontal;
  static const notifyIcon = HugeIcons.strokeRoundedNotification03;
  static const menuIcon = HugeIcons.strokeRoundedMenuSquare;
  static const supportIcon = HugeIcons.strokeRoundedInformationCircle;
  static const infoIcon = HugeIcons.strokeRoundedMail01;
  static const deleteIcon = HugeIcons.strokeRoundedDelete02;
  static const deleteXIcon = HugeIcons.strokeRoundedCancel01;
  static const arrowLeftIcon = HugeIcons.strokeRoundedArrowLeft01;
  static const arrowLeft2Icon = HugeIcons.strokeRoundedArrowLeft02;
  static const starIcon = HugeIcons.strokeRoundedStar;
  static const arrowDownIcon = HugeIcons.strokeRoundedArrowDown01;
  static const addToCartIcon = HugeIcons.strokeRoundedShoppingCartAdd02;
  static const deliveryDelayIcon = HugeIcons.strokeRoundedDeliveryDelay01;
  static const deliveredIcon = HugeIcons.strokeRoundedPackageDelivered;
  static const deliveryCancelIcon = HugeIcons.strokeRoundedBookmarkRemove01;
  static const deliveringCancelIcon = HugeIcons.strokeRoundedDeliveryTruck01;
  static const boyIcon = HugeIcons.strokeRoundedBabyBoyDress;
  static const girlIcon = HugeIcons.strokeRoundedBabyGirlDress;
  static const shoesIcon = HugeIcons.strokeRoundedRunningShoes;
  static const neckLaceIcon = HugeIcons.strokeRoundedNecklace;
  static const beautyIcon = HugeIcons.strokeRoundedAiBeautify;
  static const arrowRightIcon = HugeIcons.strokeRoundedArrowRight01;
  static const giftIcon = HugeIcons.strokeRoundedGift;
  static const imageIcon = HugeIcons.strokeRoundedImage02;
  static const cameraIcon = HugeIcons.strokeRoundedCamera01;
  static const thumbsUpIcon = HugeIcons.strokeRoundedThumbsUp;
  static const locationIcon = HugeIcons.strokeRoundedLocation01;
  static const paymentMethodIcon = HugeIcons.strokeRoundedCreditCardPos;
  static const couponIcon = HugeIcons.strokeRoundedCouponPercent;
  static const whiteListIcon = HugeIcons.strokeRoundedHeartCheck;
  static const rateIcon = HugeIcons.strokeRoundedStarHalf;
  static const logoutIcon = HugeIcons.strokeRoundedLogout03;
  static const cartIcon = HugeIcons.strokeRoundedShoppingCart01;
  static const tickIcon = HugeIcons.strokeRoundedCheckmarkCircle01;
  static const plusIcon = HugeIcons.strokeRoundedPlusSign;
}
